name: dailyRun

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          presist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - name: Run script
        run: node daily.js
  
